"""added password column in disabled and volunteer

Revision ID: bc59d347158e
Revises: 0b189ea2a166
Create Date: 2021-03-19 21:24:54.497265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc59d347158e'
down_revision = '0b189ea2a166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disabled', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('volunteer', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'password_hash')
    op.drop_column('disabled', 'password_hash')
    # ### end Alembic commands ###
